name: "Python and Terraform Checks"

on: 
  push:
    branch:
      - main
  pull_request:
    branch:
      - main

jobs:
  checks:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }} 
      - uses: 'google-github-actions/setup-gcloud@v1'
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |-
          pip install pylint==2.14.4 black==22.6.0 isort==5.10.1 
      - run: make check